version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "3030:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx.d/default.conf
    depends_on:
      - app
  app:
    build: ./photo-social-backend/app
    ports:
      - "5000:5000"
    #volumes:
    #  - ./app:/usr/src/app
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - db-data:/data/db
volumes:
  db-data: